name: Pull Request
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      # check out repository code and setup node
      - name: Checkout
        uses: actions/checkout@v1
      # install dependencies and run semantic-release
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm i
      - name: Lint & test
        run: npm run lint && npm run test
      - name: Release test
        env:
          GITHUB_HEAD_REF: $GITHUB_HEAD_REF
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --dry-run --debug -b $GITHUB_HEAD_REF
